#!/usr/bin/perl
use AppMercado;

#INFO: XXX

logm("DBG",9,"Comienzo de reporte",);

my $mem={};
my $tx=dbTxStart();
print "<HTML><BODY>";
dbFindFold('T="deptos" AND TIPO="CARACTERISTICAS"',{},['NOMBRE'],\&loadMem);
dbTxCommit($tx,0,'OK');


foreach $depto (keys %mem) {
print "<p>Departamento: $depto";
print "<p>Amenities:";
print $mem{$depto}->{'AMENITIES'};
}

print "</BODY></HTML>";


sub ind_report {
	my ($val,$dr)=@_;
	my $args={};
	$args{'EDIFICIO'}=$val;
	$args{'AMENITIES'}=join('<li>',@{$dr->{'AMENITIES'}});
	my $template="<p><b>Edificio: $args{'EDIFICIO'}</b><p><b>Amenities:</b><ul><li>$args{'AMENITIES'}</ul>\n\n";
	print $template;
}


sub loadMem {
        my ($dr)= @_;
	my %amenities;
	my %temp;
	my %d=%{$dr->{'DEPTOS'}}; 
	
	#A:Tengo a $d que es un hash del depto
        my %args= (split(/[\=\|]/,$d{'AMENITIES'}));
        while((my $key, my $value) = each(%args)) {
        	if($value eq 'SI'){
                	$amenities{$key}= $value; 
                        }
	}
	
	$temp{'AMENITIES'}= join('<li>',keys (%amenities));
	$mem{$d{'NOMBRE'}}->{'AMENITIES'}=$temp{'AMENITIES'};
	#logm("LOOP",9,"DATA: #1",\%mem);
}

